# Generated by Django 2.2.6 on 2019-10-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.CharField(max_length=1000)),
                ('icon02', models.CharField(max_length=300)),
            ],
        ),
    ]
