# Generated by Django 2.2.6 on 2019-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191025_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon02',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ImageField(default=1, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
