# Generated by Django 2.2.6 on 2019-10-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191025_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon02',
        ),
    ]
